module.exports = {
  ALL: {symbol: 'Lek', htmlCode: '&#76;&#101;&#107;', name: 'Albania Lek'},
  AFN: {symbol: '؋', htmlCode: '&#1547;', name: 'Afghanistan Afghani'},
  ARS: {symbol: '$', htmlCode: '&#36;', name: 'Argentina Peso'},
  AWG: {symbol: 'ƒ', htmlCode: '&#402;', name: 'Aruba Guilder'},
  AUD: {symbol: '$', htmlCode: '&#36;', name: 'Australia Dollar'},
  AZN: {symbol: 'ман', htmlCode: '&#1084;&#1072;&#1085;', name: 'Azerbaijan New Manat'},
  BSD: {symbol: '$', htmlCode: '&#36;', name: 'Bahamas Dollar'},
  BBD: {symbol: '$', htmlCode: '&#36;', name: 'Barbados Dollar'},
  BYR: {symbol: 'p.', htmlCode: '&#112;&#46;', name: 'Belarus Ruble'},
  BZD: {symbol: 'BZ$', htmlCode: '&#66;&#90;&#36;', name: 'Belize Dollar'},
  BMD: {symbol: '$', htmlCode: '&#36;', name: 'Bermuda Dollar'},
  BOB: {symbol: '$b', htmlCode: '&#36;&#98;', name: 'Bolivia Boliviano'},
  BAM: {symbol: 'KM', htmlCode: '&#75;&#77;', name: 'Bosnia and Herzegovina Convertible Marka'},
  BWP: {symbol: 'P', htmlCode: '&#80;', name: 'Botswana Pula'},
  BGN: {symbol: 'лв', htmlCode: '&#1083;&#1074;', name: 'Bulgaria Lev'},
  BRL: {symbol: 'R$', htmlCode: '&#82;&#36;', name: 'Brazil Real'},
  BND: {symbol: '$', htmlCode: '&#36;', name: 'Brunei Darussalam Dollar'},
  KHR: {symbol: '៛', htmlCode: '&#6107;', name: 'Cambodia Riel'},
  CAD: {symbol: '$', htmlCode: '&#36;', name: 'Canada Dollar'},
  KYD: {symbol: '$', htmlCode: '&#36;', name: 'Cayman Islands Dollar'},
  CLP: {symbol: '$', htmlCode: '&#36;', name: 'Chile Peso'},
  CNY: {symbol: '¥', htmlCode: '&#165;', name: 'China Yuan Renminbi'},
  COP: {symbol: '$', htmlCode: '&#36;', name: 'Colombia Peso'},
  CRC: {symbol: '₡', htmlCode: '&#8353;', name: 'Costa Rica Colon'},
  HRK: {symbol: 'kn', htmlCode: '&#107;&#110;', name: 'Croatia Kuna'},
  CUP: {symbol: '₱', htmlCode: '&#8369;', name: 'Cuba Peso'},
  CZK: {symbol: 'Kč', htmlCode: '&#75;&#269;', name: 'Czech Republic Koruna'},
  DKK: {symbol: 'kr', htmlCode: '&#107;&#114;', name: 'Denmark Krone'},
  DOP: {symbol: 'RD$', htmlCode: '&#82;&#68;&#36;', name: 'Dominican Republic Peso'},
  XCD: {symbol: '$', htmlCode: '&#36;', name: 'East Caribbean Dollar'},
  EGP: {symbol: '£', htmlCode: '&#163;', name: 'Egypt Pound'},
  SVC: {symbol: '$', htmlCode: '&#36;', name: 'El Salvador Colon'},
  EUR: {symbol: '€', htmlCode: '&#8364;', name: 'Euro Member Countries'},
  FKP: {symbol: '£', htmlCode: '&#163;', name: 'Falkland Islands (Malvinas) Pound'},
  FJD: {symbol: '$', htmlCode: '&#36;', name: 'Fiji Dollar'},
  GHS: {symbol: '¢', htmlCode: '&#162;', name: 'Ghana Cedi'},
  GIP: {symbol: '£', htmlCode: '&#163;', name: 'Gibraltar Pound'},
  GTQ: {symbol: 'Q', htmlCode: '&#81;', name: 'Guatemala Quetzal'},
  GGP: {symbol: '£', htmlCode: '&#163;', name: 'Guernsey Pound'},
  GYD: {symbol: '$', htmlCode: '&#36;', name: 'Guyana Dollar'},
  HNL: {symbol: 'L', htmlCode: '&#76;', name: 'Honduras Lempira'},
  HKD: {symbol: '$', htmlCode: '&#36;', name: 'Hong Kong Dollar'},
  HUF: {symbol: 'Ft', htmlCode: '&#70;&#116;', name: 'Hungary Forint'},
  ISK: {symbol: 'kr', htmlCode: '&#107;&#114;', name: 'Iceland Krona'},
  IDR: {symbol: 'Rp', htmlCode: '&#82;&#112;', name: 'Indonesia Rupiah'},
  IRR: {symbol: '﷼', htmlCode: '&#65020;', name: 'Iran Rial'},
  IMP: {symbol: '£', htmlCode: '&#163;', name: 'Isle of Man Pound'},
  ILS: {symbol: '₪', htmlCode: '&#8362;', name: 'Israel Shekel'},
  JMD: {symbol: 'J$', htmlCode: '&#74;&#36;', name: 'Jamaica Dollar'},
  JPY: {symbol: '¥', htmlCode: '&#165;', name: 'Japan Yen'},
  JEP: {symbol: '£', htmlCode: '&#163;', name: 'Jersey Pound'},
  KZT: {symbol: 'лв', htmlCode: '&#1083;&#1074;', name: 'Kazakhstan Tenge'},
  KPW: {symbol: '₩', htmlCode: '&#8361;', name: 'Korea (North) Won'},
  KGS: {symbol: 'лв', htmlCode: '&#1083;&#1074;', name: 'Kyrgyzstan Som'},
  LAK: {symbol: '₭', htmlCode: '&#8365;', name: 'Laos Kip'},
  LBP: {symbol: '£', htmlCode: '&#163;', name: 'Lebanon Pound'},
  LRD: {symbol: '$', htmlCode: '&#36;', name: 'Liberia Dollar'},
  MKD: {symbol: 'ден', htmlCode: '&#1076;&#1077;&#1085;', name: 'Macedonia Denar'},
  MYR: {symbol: 'RM', htmlCode: '&#82;&#77;', name: 'Malaysia Ringgit'},
  MUR: {symbol: '₨', htmlCode: '&#8360;', name: 'Mauritius Rupee'},
  MXN: {symbol: '$', htmlCode: '&#36;', name: 'Mexico Peso'},
  MNT: {symbol: '₮', htmlCode: '&#8366;', name: 'Mongolia Tughrik'},
  MZN: {symbol: 'MT', htmlCode: '&#77;&#84;', name: 'Mozambique Metical'},
  NAD: {symbol: '$', htmlCode: '&#36;', name: 'Namibia Dollar'},
  NPR: {symbol: '₨', htmlCode: '&#8360;', name: 'Nepal Rupee'},
  ANG: {symbol: 'ƒ', htmlCode: '&#402;', name: 'Netherlands Antilles Guilder'},
  NZD: {symbol: '$', htmlCode: '&#36;', name: 'New Zealand Dollar'},
  NIO: {symbol: 'C$', htmlCode: '&#67;&#36;', name: 'Nicaragua Cordoba'},
  NGN: {symbol: '₦', htmlCode: '&#8358;', name: 'Nigeria Naira'},
  NOK: {symbol: 'kr', htmlCode: '&#107;&#114;', name: 'Norway Krone'},
  OMR: {symbol: '﷼', htmlCode: '&#65020;', name: 'Oman Rial'},
  PKR: {symbol: '₨', htmlCode: '&#8360;', name: 'Pakistan Rupee'},
  PAB: {symbol: 'B/.', htmlCode: '&#66;&#47;&#46;', name: 'Panama Balboa'},
  PYG: {symbol: 'Gs', htmlCode: '&#71;&#115;', name: 'Paraguay Guarani'},
  PEN: {symbol: 'S/.', htmlCode: '&#83;&#47;&#46;', name: 'Peru Nuevo Sol'},
  PHP: {symbol: '₱', htmlCode: '&#8369;', name: 'Philippines Peso'},
  PLN: {symbol: 'zł', htmlCode: '&#122;&#322;', name: 'Poland Zloty'},
  QAR: {symbol: '﷼', htmlCode: '&#65020;', name: 'Qatar Riyal'},
  RON: {symbol: 'lei', htmlCode: '&#108;&#101;&#105;', name: 'Romania New Leu'},
  RUB: {symbol: 'руб', htmlCode: '&#1088;&#1091;&#1073;', name: 'Russia Ruble'},
  SHP: {symbol: '£', htmlCode: '&#163;', name: 'Saint Helena Pound'},
  SAR: {symbol: '﷼', htmlCode: '&#65020;', name: 'Saudi Arabia Riyal'},
  RSD: {symbol: 'Дин.', htmlCode: '1044, 1080, 1085, 46', name: 'Serbia Dinar'},
  SCR: {symbol: '₨', htmlCode: '&#8360;', name: 'Seychelles Rupee'},
  SGD: {symbol: '$', htmlCode: '&#36;', name: 'Singapore Dollar'},
  SBD: {symbol: '$', htmlCode: '&#36;', name: 'Solomon Islands Dollar'},
  SOS: {symbol: 'S', htmlCode: '&#83;', name: 'Somalia Shilling'},
  ZAR: {symbol: 'R', htmlCode: '&#82;', name: 'South Africa Rand'},
  KRW: {symbol: '₩', htmlCode: '&#8361;', name: 'Korea (South) Won'},
  LKR: {symbol: '₨', htmlCode: '&#8360;', name: 'Sri Lanka Rupee'},
  SEK: {symbol: 'kr', htmlCode: '&#107;&#114;', name: 'Sweden Krona'},
  CHF: {symbol: 'CHF', htmlCode: '&#67;&#72;&#70;', name: 'Switzerland Franc'},
  SRD: {symbol: '$', htmlCode: '&#36;', name: 'Suriname Dollar'},
  SYP: {symbol: '£', htmlCode: '&#163;', name: 'Syria Pound'},
  TWD: {symbol: 'NT$', htmlCode: '&#78;&#84;&#36;', name: 'Taiwan New Dollar'},
  THB: {symbol: '฿', htmlCode: '&#3647;', name: 'Thailand Baht'},
  TTD: {symbol: 'TT$', htmlCode: '&#84;&#84;&#36;', name: 'Trinidad and Tobago Dollar'},
  TVD: {symbol: '$', htmlCode: '&#36;', name: 'Tuvalu Dollar'},
  UAH: {symbol: '₴', htmlCode: '&#8372;', name: 'Ukraine Hryvnia'},
  GBP: {symbol: '£', htmlCode: '&#163;', name: 'United Kingdom Pound'},
  USD: {symbol: '$', htmlCode: '&#36;', name: 'United States Dollar'},
  UYU: {symbol: '$U', htmlCode: '&#36;&#85;', name: 'Uruguay Peso'},
  UZS: {symbol: 'лв', htmlCode: '&#1083;&#1074;', name: 'Uzbekistan Som'},
  VEF: {symbol: 'Bs', htmlCode: '&#66;&#115;', name: 'Venezuela Bolivar'},
  VND: {symbol: '₫', htmlCode: '&#8363;', name: 'Viet Nam Dong'},
  YER: {symbol: '﷼', htmlCode: '&#65020;', name: 'Yemen Rial'},
  ZWD: {symbol: 'Z$', htmlCode: '&#90;&#36;', name: 'Zimbabwe Dollar'}
}
